### ISSUE TITLE
Device Registration is not working again.

### ISSUE THREAD

**Issue by jackgassett** [alvieboy/ZPUino#22]
Making the change as shown in line 9 of this commit reports that the device is already registered.
https://github.com/GadgetFactory/DesignLab/commit/24749c728a9bd9d42cac357227b812e6eb4f466b

I have disabled lines 14-20 in DeviceRegistry.cpp in DesignLab for the time being.

**Comment by alvieboy** [comment]
This looks like a very odd git merge on your tree. It's registering the device twice. Closing this.
